name: build

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build
    - run: cargo test

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test -- --nocapture
